import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import costItemsRouter from "./cost-items";
import budgetsRouter from "./budgets";
import budgetItemsRouter from "./budget-items";
import dashboardRouter from "./dashboard";
import paymentsRouter from "./payments";
import vendorGroupsRouter from "./vendor-groups";
import vendorsRouter from "./vendors";
import paymentAssessmentsRouter from "./payment-assessments";
import workTypesRouter from "./work-types";
import estimatesRouter from "./estimates";
import clientsRouter from "./clients";
import companySettingsRouter from "./company-settings";
import invoicesRouter from "./invoices";
import invoicePaymentsRouter from "./invoice-payments";
import constructionHistoriesRouter from "./construction-histories";
import purchaseOrdersRouter from "./purchase-orders";
import purchaseInvoicesRouter from "./purchase-invoices";
import unitPricesRouter from "./unit-prices";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/projects", projectsRouter);
router.use("/projects/:id/budget-items", budgetItemsRouter);
router.use("/cost-items", costItemsRouter);
router.use("/budgets", budgetsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/payments", paymentsRouter);
router.use("/vendor-groups", vendorGroupsRouter);
router.use("/vendors", vendorsRouter);
router.use("/payment-assessments", paymentAssessmentsRouter);
router.use("/work-types", workTypesRouter);
router.use("/estimates", estimatesRouter);
router.use("/clients", clientsRouter);
router.use("/company-settings", companySettingsRouter);
router.use("/invoices", invoicesRouter);
router.use("/invoices/:id/payments", invoicePaymentsRouter);
router.use("/projects/:projectId/construction-history", constructionHistoriesRouter);
router.use("/purchase-orders", purchaseOrdersRouter);
router.use("/purchase-invoices", purchaseInvoicesRouter);
router.use("/unit-prices", unitPricesRouter);

export default router;
